config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'download', to: 'config_creators#download'
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/home/about" => "homes#about", as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #ApplicationControllerは全てのコントローラに対する処理を行う権限を持ってるよ
  #deviseのコントローラは編集できないよ
  before_action :authenticate_user!, except: [:top, :about]
  #全てのアクションの前にユーザーがログインしているか確認するよ
  #ただし、topアクションは除くよ
  before_action :configure_permitted_parameters, if: :devise_controller?
  #（アプリ２の６章）devise利用の機能（ユーザ登録、ログイン認証など）が使われる前に、
  #configure_permitted_parametersメソッドが実行されるよ

  def after_sign_in_path_for(resource)#サインインした後にアクセスするパスは
    user_path(current_user.id)#（現在ログインしているユーザーのidの）ユーザーパスつまりユーザー詳細画面に行くよ
  end

  def after_sign_out_path_for(resource)#サインアウトした後にアクセスするパスは
    root_path#ルートパスだよつまりトップ画面にアクセスするよ
  end

  private#ここから下はこのコントローラでしか呼び出せないよ？

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  protected#ここから下は呼び出された他のコントローラからも参照できるよ

  def configure_permitted_parameters#ストロングパラメータと同じ機能だよ
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end#ユーザー登録（sign_up）の際に、emailのデータ操作を許可しているよ
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id#@book.user_id イコール current_user.idではない。@book.user_idに現在ログインしているuserのidを代入するということ
    @user = current_user
    @books = Book.all
    if @book.save
      redirect_to book_path(@book.id)
      flash[:success] = "You have created book successfully."
    else
      render :index
    end
  end

  def index
    @book = Book.new #部分テンプレート用
    @user = current_user #部分テンプレート用
    @books = Book.all #一覧を表示させるためのもの
  end

  def show
    @new = Book.new  #部分テンプレート用
    @book = Book.find(params[:id])#これはほぼ決まった形なので変えない
  end

  def edit
    book = Book.find(params[:id])
    user = User.find(book.user.id)
    unless user.id == current_user.id
      redirect_to books_path
    end
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:updated] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/config_creators_controller.rb
class ConfigCreatorsController < ApplicationController

  def download
    download_file_name = "public/master/harahetta.JPG"
    send_file download_file_name
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books#これで、ユーザーに関連した本の投稿が取得できる。booksとなっているのはmodelにhas_many :booksと書いているから。
  end                   #@user.booksは複数の投稿が入った配列になっている。

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:update] = "You have updated user successfully."
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/config_creators_helper.rb
module ConfigCreatorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
        <h2>User info</h2>
        <table class="table">
          <tr><%= image_tag user.get_profile_image(100, 100) %></tr>
          <tr><th><strong>name</strong></th><th><%= user.name %></th></tr>
          <tr><th><strong>introduction</strong></th><th><%= user.introduction %></th></tr>
        </table>
        <div class="row">
         <%= link_to edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog"></i>
         <% end %>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: book do |f| %>
          <div class="form-group">
            <label for="inputTitle">Title</label>
            <p><%= f.text_field :title, id:"inputTitle", class:"form-control book_title" %></p>
          </div>
          <div class="form-group">
            <label for="inputOpinion">Opinion</label>
            <p><%= f.text_area :body, id:"inputOpinion", class:"form-control book_body" %></p>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          </div>
        <% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <%= @book.errors.count %> errors prohibited this obj from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title", id:"book_title" %>
        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <%= f.text_area :body, class:"form-control book_body" %>
        </div>
        <div class="form-group">
        <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
        <div>
        <%= link_to "Show", book_path(@book.id) %>
        <span>|</span>
        <%= link_to "Back", books_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3"><!--ここから左側部分-->
        <%= render 'book', user: @user, book: @book %>
      </div><!--ここまでが左側部分-->
      <div class="col-md-8 offset-md-1"><!--ここから右側部分-->
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %><!--user.get_profile_image(100, 100)でワンセット-->
                  <%= image_tag book.user.get_profile_image(100, 100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= button_to 'ファイルのダウンロード', download_path, method: :get, class: "btn btn-default" %>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'book', user: @book.user, book: @new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@book.user) do %>
              <%= image_tag @book.user.get_profile_image(100, 100) %>
            <% end %>
            <br>
            <%= link_to user_path(@book.user) do %>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
            <% end %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <td>
            <% if @book.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
            <% end %>
          </td>
          <td>
            <% if @book.user == current_user %>
              <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-sm btn-danger" %>
            <% end %><!-- destroyと一緒にかくbook_path(@book.id)の意味がよくわからない-->
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i>
        <strong>Bookers!!</strong>
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<p id-"notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !!
      </h1>
      <p>In <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      ,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign-in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %><!--クロスサイトリクエストフォージェリーからRailsが守ってくれる-->
    <%= csp_meta_tag %><!--コンテントセキュリティポリシー、セキュリティのウェブの仕様-->

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                       aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %><!--ログイン済みならelseまでの処理-->
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              &nbsp;
              <li class="nav-item">
                <%= link_to users_path, class:"nav-link text-light" do %>
                  <i class="fas fa-users"></i>
                  Users
                <% end %>
              </li>
              &nbsp;
              <li class="nav-item">
                <%= link_to books_path, class:"nav-link text-light" do %>
                  <i class="fas fa-book-open"></i>
                  Books
                <% end %>
              </li>
              &nbsp;
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i>
                  Log out
                <% end %>
              </li>
              <% else %><!--ログインしてないならendまでの処理-->
              <li class="nav-item">
                <%= link_to root_path, class:"nav-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class:"nav-link text-light" do %>
                  <i class="fas fa-link"></i>
                  About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i>
                  Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %><!--この記述でフラッシュメッセージが記述できる、deviseに元から実装されてるので-->
      <%= yield %>
    </main>
    <footer class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
      <%= @user.errors.count %> errors prohibited this obj from being saved:
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label><!--labelはフォームの項目名と構成部品を関連づける-->
          <%= f.text_field :name, class:"form-control name", id:"user_name" %>
          <!--ブラウザでNameをクリックすることを入力フォームをクリックすることと同じ意味にする-->
          <!--autofocus属性はデフォルトでその要素にフォーカスが当たるようにする-->
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, class:"form-control-file user_image", accept: "image/*" %>
        </div>
        <div>
          <label for="user_introduction">Introduction</label>
          <p><%= f.text_area :introduction, class:"form-control introduction", id:"user_introduction" %></p>
          <!--placeholderは入力欄に入力例などの仮のテキストを入れる-->
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3"><!--ここから左側部分-->
      <%= render 'books/book', user: @user, book: @book %>
    </div><!--ここまでが左側部分-->
    <div class="col-md-8 offset-md-1"><!--ここから右側部分-->
      <h2>Users</h2>
      <table class="table">
        <thead>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100, 100) %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/book', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image(100, 100) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>